//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoundUp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoundUp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://windowsphone.com/s?appId=0c4920e4-ffa6-4e77-bb93-5d490e832204.
        /// </summary>
        public static string _AppLinkInStore {
            get {
                return ResourceManager.GetString("_AppLinkInStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0c4920e4-ffa6-4e77-bb93-5d490e832204.
        /// </summary>
        public static string _MapApplicationId {
            get {
                return ResourceManager.GetString("_MapApplicationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GgRLyFHFs1z2h6zeeWjE_Q.
        /// </summary>
        public static string _MapAuthenticationToken {
            get {
                return ResourceManager.GetString("_MapAuthenticationToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rnKizRbmtqcMZjwCTCsoIfVgVEJWON18.
        /// </summary>
        public static string _RoundUpAzureMobileServiceKey {
            get {
                return ResourceManager.GetString("_RoundUpAzureMobileServiceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://roundup.azure-mobile.net/.
        /// </summary>
        public static string _RoundUpAzureMobileServiceUri {
            get {
                return ResourceManager.GetString("_RoundUpAzureMobileServiceUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        public static string About_DevelopedBy {
            get {
                return ResourceManager.GetString("About_DevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RArcher Software Ltd..
        /// </summary>
        public static string About_DevelopedBy_Content {
            get {
                return ResourceManager.GetString("About_DevelopedBy_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://rarcher.azurewebsites.net/App/Rndup.
        /// </summary>
        public static string About_DevelopedBy_Link {
            get {
                return ResourceManager.GetString("About_DevelopedBy_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string About_License {
            get {
                return ResourceManager.GetString("About_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string About_PrivacyPolicy {
            get {
                return ResourceManager.GetString("About_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full privacy policy.
        /// </summary>
        public static string About_PrivacyPolicy_Content {
            get {
                return ResourceManager.GetString("About_PrivacyPolicy_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://rarcher.azurewebsites.net/App/RndupPrivacy.
        /// </summary>
        public static string About_PrivacyPolicy_Link {
            get {
                return ResourceManager.GetString("About_PrivacyPolicy_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        public static string About_Purchase {
            get {
                return ResourceManager.GetString("About_Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to purchase.
        /// </summary>
        public static string About_Purchase_Content {
            get {
                return ResourceManager.GetString("About_Purchase_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string About_RateAndReview {
            get {
                return ResourceManager.GetString("About_RateAndReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to review.
        /// </summary>
        public static string About_RateAndReview_Content {
            get {
                return ResourceManager.GetString("About_RateAndReview_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string About_Support {
            get {
                return ResourceManager.GetString("About_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support site.
        /// </summary>
        public static string About_Support_Content {
            get {
                return ResourceManager.GetString("About_Support_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://rarcher.azurewebsites.net/App/RndupSupport.
        /// </summary>
        public static string About_Support_Link {
            get {
                return ResourceManager.GetString("About_Support_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full usage terms and conditions.
        /// </summary>
        public static string About_TandC_Content {
            get {
                return ResourceManager.GetString("About_TandC_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://rarcher.azurewebsites.net/App/RndupTerms.
        /// </summary>
        public static string About_TandC_Link {
            get {
                return ResourceManager.GetString("About_TandC_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        public static string About_Version_Content {
            get {
                return ResourceManager.GetString("About_Version_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the roundup invite code you were sent, or paste the entire invite message into the box below:.
        /// </summary>
        public static string AcceptInvitePrompt {
            get {
                return ResourceManager.GetString("AcceptInvitePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your are now connected to {0}. 
        ///
        ///They will be able to see your location until the session ends (when you arrive), or you cancel..
        /// </summary>
        public static string AcceptInviteSuccess {
            get {
                return ResourceManager.GetString("AcceptInviteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string AcceptInviteSuccessTitle {
            get {
                return ResourceManager.GetString("AcceptInviteSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All invitees arrived..
        /// </summary>
        public static string AllInviteesArrived {
            get {
                return ResourceManager.GetString("AllInviteesArrived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session completed..
        /// </summary>
        public static string AllInviteesArrivedSessionComplete {
            get {
                return ResourceManager.GetString("AllInviteesArrivedSessionComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All invitees have cancelled their participation in the roundup session.
        ///
        ///Do you want to end the session now?.
        /// </summary>
        public static string AllInviteesHaveCancelled {
            get {
                return ResourceManager.GetString("AllInviteesHaveCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No invitees.
        /// </summary>
        public static string AllInviteesHaveCancelledTitle {
            get {
                return ResourceManager.GetString("AllInviteesHaveCancelledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All invitees have cancelled..
        /// </summary>
        public static string AllInviteesHaveCancelledToast {
            get {
                return ResourceManager.GetString("AllInviteesHaveCancelledToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session ended.
        /// </summary>
        public static string AllInviteesHaveCancelledToastTitle {
            get {
                return ResourceManager.GetString("AllInviteesHaveCancelledToastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a FULL license to use roundup. This entitles you to free updates to this version. 
        ///
        ///Thank you very much for your support, it&apos;s much appreciated!.
        /// </summary>
        public static string AlreadyPurchased {
            get {
                return ResourceManager.GetString("AlreadyPurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full License.
        /// </summary>
        public static string AlreadyPurchasedTitle {
            get {
                return ResourceManager.GetString("AlreadyPurchasedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to roundup.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The invite code you provided doesn&apos;t seem to be correct. 
        ///
        ///If you received the invite via SMS or email you can copy  the entire message into the invite code box..
        /// </summary>
        public static string BadInviteCode {
            get {
                return ResourceManager.GetString("BadInviteCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad invite code.
        /// </summary>
        public static string BadInviteCodeTitle {
            get {
                return ResourceManager.GetString("BadInviteCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///For an even better experience, get roundup from the Windows Phone Store:
        ///
        ///.
        /// </summary>
        public static string BingMapsPostamble {
            get {
                return ResourceManager.GetString("BingMapsPostamble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {alias} is sharing a location with you with via roundup and Bing maps:
        ///
        ///.
        /// </summary>
        public static string BingMapsPreamble {
            get {
                return ResourceManager.GetString("BingMapsPreamble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.bing.com/maps/?v=2&amp;cp={0}~{1}&amp;lvl=18&amp;sp=point.{0}_{1}_{2}_{3}.
        /// </summary>
        public static string BingMapsUri {
            get {
                return ResourceManager.GetString("BingMapsUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A link which can show your current location using Bing Maps has been added to the clipboard. 
        ///
        ///You can send this link to a friend so they can view your current location using any device that can access the web. .
        /// </summary>
        public static string BingMapsViaClipboard {
            get {
                return ResourceManager.GetString("BingMapsViaClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email message which includes a link to show your current location using Bing Maps has been created. 
        ///
        ///You can send this link to a friend so they can view your current location using any device that can access the web.
        ///
        ///Click OK to view the message in the email composer and select the person(s) you wish to send it to..
        /// </summary>
        public static string BingMapsViaEmail {
            get {
                return ResourceManager.GetString("BingMapsViaEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An SMS message which includes a link to show your current location using Bing Maps has been created. 
        ///
        ///You can send this link to a friend so they can view your current location using any device that can access the web.
        ///
        ///Click OK to view the message in the SMS message composer and select the person(s) you wish to send it to..
        /// </summary>
        public static string BingMapsViaSms {
            get {
                return ResourceManager.GetString("BingMapsViaSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share via Bing Maps.
        /// </summary>
        public static string BingMapsViaXTitle {
            get {
                return ResourceManager.GetString("BingMapsViaXTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel your participation in the current roundup session. 
        ///
        ///Are you sure?.
        /// </summary>
        public static string CancelInviteeSession {
            get {
                return ResourceManager.GetString("CancelInviteeSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel the current roundup session? 
        ///
        ///If you do this a notification will be sent to all invitees, cancelling their participation in the session.
        ///
        ///Are you sure?.
        /// </summary>
        public static string CancelInviterSession {
            get {
                return ResourceManager.GetString("CancelInviterSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Session.
        /// </summary>
        public static string CancelSessionTitle {
            get {
                return ResourceManager.GetString("CancelSessionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel the current roundup session? 
        ///
        ///We are currently waiting for a push notification containing the session ID (the session has not finished the start-up process).
        ///
        ///Are you sure?.
        /// </summary>
        public static string CancelUnstartedSession {
            get {
                return ResourceManager.GetString("CancelUnstartedSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error cancelling the session. Some invitees may not have received a notification..
        /// </summary>
        public static string CannotCancelSession {
            get {
                return ResourceManager.GetString("CannotCancelSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error cancelling session.
        /// </summary>
        public static string CannotCancelSessionTitle {
            get {
                return ResourceManager.GetString("CannotCancelSessionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change the meetup location with the roundup cloud service. 
        ///
        ///Try again later..
        /// </summary>
        public static string CannotChangeRoundUpPoint {
            get {
                return ResourceManager.GetString("CannotChangeRoundUpPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t change location.
        /// </summary>
        public static string CannotChangeRoundUpPointTitle {
            get {
                return ResourceManager.GetString("CannotChangeRoundUpPointTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can&apos;t get your location right now, but we&apos;ll keep trying in the background.
        ///
        ///The GPS sensors in your device may not work correctly if you are indoors, or there are a lot a high buildings nearby..
        /// </summary>
        public static string CannotGetLocation {
            get {
                return ResourceManager.GetString("CannotGetLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get your location.
        /// </summary>
        public static string CannotGetLocationTitle {
            get {
                return ResourceManager.GetString("CannotGetLocationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, unable to get the route to the roundup point.
        ///
        ///However, {0} is located at {1}. 
        ///
        ///This location is marked on the map and is {2} away from your current location..
        /// </summary>
        public static string CannotGetRoute {
            get {
                return ResourceManager.GetString("CannotGetRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route not found.
        /// </summary>
        public static string CannotGetRouteTitle {
            get {
                return ResourceManager.GetString("CannotGetRouteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start a new invitee session with the roundup cloud service. 
        ///
        ///Try again later..
        /// </summary>
        public static string CannotStartInviteeSession {
            get {
                return ResourceManager.GetString("CannotStartInviteeSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoundUp session error.
        /// </summary>
        public static string CannotStartInviteeSessionTitle {
            get {
                return ResourceManager.GetString("CannotStartInviteeSessionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start a new session with the roundup cloud service. 
        ///
        ///Try again later..
        /// </summary>
        public static string CannotStartNewSession {
            get {
                return ResourceManager.GetString("CannotStartNewSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error starting new session.
        /// </summary>
        public static string CannotStartNewSessionTitle {
            get {
                return ResourceManager.GetString("CannotStartNewSessionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t create a new session because you are already an invitee in an existing roundup session.
        ///
        ///You may share your location using Bing maps via SMS or email while you are participating in a roundup session. 
        ///
        ///Alternatively, cancel your participation in the current session, then create a new session..
        /// </summary>
        public static string CantCreateNewSessionWhenInvitee {
            get {
                return ResourceManager.GetString("CantCreateNewSessionWhenInvitee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create new session.
        /// </summary>
        public static string CantCreateNewSessionWhenInviteeTitle {
            get {
                return ResourceManager.GetString("CantCreateNewSessionWhenInviteeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to center on map.
        /// </summary>
        public static string CenterInviteeOnMap {
            get {
                return ResourceManager.GetString("CenterInviteeOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The roundup location has been successfully changed. 
        ///
        ///All invitees have been sent update notifications..
        /// </summary>
        public static string ChangeRoundUpPointSuccess {
            get {
                return ResourceManager.GetString("ChangeRoundUpPointSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location changed OK.
        /// </summary>
        public static string ChangeRoundUpPointSuccessTitle {
            get {
                return ResourceManager.GetString("ChangeRoundUpPointSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checking network connection.
        /// </summary>
        public static string CheckingForNetworkConnection {
            get {
                return ResourceManager.GetString("CheckingForNetworkConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to close help.
        /// </summary>
        public static string CloseHelp {
            get {
                return ResourceManager.GetString("CloseHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connected.
        /// </summary>
        public static string ConnectionStatus_Connected {
            get {
                return ResourceManager.GetString("ConnectionStatus_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disconnected.
        /// </summary>
        public static string ConnectionStatus_Disconnected {
            get {
                return ResourceManager.GetString("ConnectionStatus_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End this session?.
        /// </summary>
        public static string EndSession {
            get {
                return ResourceManager.GetString("EndSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new roundup session..
        /// </summary>
        public static string HelpText01 {
            get {
                return ResourceManager.GetString("HelpText01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell your friends you want to meet up..
        /// </summary>
        public static string HelpText02 {
            get {
                return ResourceManager.GetString("HelpText02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See your friends on the map..
        /// </summary>
        public static string HelpText03 {
            get {
                return ResourceManager.GetString("HelpText03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got an invite? Just tap the link..
        /// </summary>
        public static string HelpText04 {
            get {
                return ResourceManager.GetString("HelpText04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See where to meetup..
        /// </summary>
        public static string HelpText05 {
            get {
                return ResourceManager.GetString("HelpText05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View walking or driving instructions..
        /// </summary>
        public static string HelpText06 {
            get {
                return ResourceManager.GetString("HelpText06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accepted your invite.
        /// </summary>
        public static string InviteeHasAcceptedToast {
            get {
                return ResourceManager.GetString("InviteeHasAcceptedToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Invitee.
        /// </summary>
        public static string InviteeHasAcceptedToastTitle {
            get {
                return ResourceManager.GetString("InviteeHasAcceptedToastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has arrived..
        /// </summary>
        public static string InviteeHasArrivedToast {
            get {
                return ResourceManager.GetString("InviteeHasArrivedToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival!.
        /// </summary>
        public static string InviteeHasArrivedToastTitle {
            get {
                return ResourceManager.GetString("InviteeHasArrivedToastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has cancelled their participation in this roundup session..
        /// </summary>
        public static string InviteeHasCancelledToast {
            get {
                return ResourceManager.GetString("InviteeHasCancelledToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation.
        /// </summary>
        public static string InviteeHasCancelledToastTitle {
            get {
                return ResourceManager.GetString("InviteeHasCancelledToastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is centered on the map..
        /// </summary>
        public static string InviteeIsCentered {
            get {
                return ResourceManager.GetString("InviteeIsCentered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitee centered.
        /// </summary>
        public static string InviteeIsCenteredTitle {
            get {
                return ResourceManager.GetString("InviteeIsCenteredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to roundup invite.
        /// </summary>
        public static string InviteEmailSubject {
            get {
                return ResourceManager.GetString("InviteEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been invited to meetup with {alias}. Tap the link to open the roundup app (or, open roundup and paste this msg into the accept invite box)..
        /// </summary>
        public static string InviteMessage {
            get {
                return ResourceManager.GetString("InviteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {alias} wants to meetup. .
        /// </summary>
        public static string InviteMessageShort {
            get {
                return ResourceManager.GetString("InviteMessageShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to proceed with operation because the key services listed below are turned off.
        ///
        ///You may turn these services on from the &apos;settings&apos; screen.
        ///
        ///.
        /// </summary>
        public static string KeyServicesAreOff {
            get {
                return ResourceManager.GetString("KeyServicesAreOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services disabled.
        /// </summary>
        public static string KeyServicesAreOffTitle {
            get {
                return ResourceManager.GetString("KeyServicesAreOffTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        public static string LicenseMode_Full {
            get {
                return ResourceManager.GetString("LicenseMode_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing or revoked.
        /// </summary>
        public static string LicenseMode_MissingOrRevoked {
            get {
                return ResourceManager.GetString("LicenseMode_MissingOrRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial ({0} days left) - purchase.
        /// </summary>
        public static string LicenseMode_Trial {
            get {
                return ResourceManager.GetString("LicenseMode_Trial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial (expired).
        /// </summary>
        public static string LicenseMode_TrialExpired {
            get {
                return ResourceManager.GetString("LicenseMode_TrialExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location services have been disabled. 
        ///
        ///You may turn location services on from the &apos;settings&apos; screen..
        /// </summary>
        public static string LocationServicesDisabled {
            get {
                return ResourceManager.GetString("LocationServicesDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are attempting to use roundup for a long journey of {0} km.
        ///
        ///Too avoid sending a large number of push notifications, progress updates will only be broadcast to the person who invited you every {1} km..
        /// </summary>
        public static string LongJourney {
            get {
                return ResourceManager.GetString("LongJourney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long journey.
        /// </summary>
        public static string LongJourneyTitle {
            get {
                return ResourceManager.GetString("LongJourneyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daylight mode.
        /// </summary>
        public static string MapCtrlPanel_DaylightMode {
            get {
                return ResourceManager.GetString("MapCtrlPanel_DaylightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading.
        /// </summary>
        public static string MapCtrlPanel_Heading {
            get {
                return ResourceManager.GetString("MapCtrlPanel_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landmarks.
        /// </summary>
        public static string MapCtrlPanel_Landmarks {
            get {
                return ResourceManager.GetString("MapCtrlPanel_Landmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedestrian features.
        /// </summary>
        public static string MapCtrlPanel_PedestrianFeatures {
            get {
                return ResourceManager.GetString("MapCtrlPanel_PedestrianFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitch.
        /// </summary>
        public static string MapCtrlPanel_Pitch {
            get {
                return ResourceManager.GetString("MapCtrlPanel_Pitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View mode.
        /// </summary>
        public static string MapCtrlPanel_ViewMode {
            get {
                return ResourceManager.GetString("MapCtrlPanel_ViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string MapCtrlPanel_Zoom {
            get {
                return ResourceManager.GetString("MapCtrlPanel_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aerial.
        /// </summary>
        public static string MapViewMode_Aerial {
            get {
                return ResourceManager.GetString("MapViewMode_Aerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid.
        /// </summary>
        public static string MapViewMode_Hybrid {
            get {
                return ResourceManager.GetString("MapViewMode_Hybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road.
        /// </summary>
        public static string MapViewMode_Road {
            get {
                return ResourceManager.GetString("MapViewMode_Road", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain.
        /// </summary>
        public static string MapViewMode_Terrain {
            get {
                return ResourceManager.GetString("MapViewMode_Terrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accept.
        /// </summary>
        public static string MenuItem_Accept {
            get {
                return ResourceManager.GetString("MenuItem_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string MenuItem_Cancel {
            get {
                return ResourceManager.GetString("MenuItem_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center location on map.
        /// </summary>
        public static string MenuItem_CenterCurrentLocation {
            get {
                return ResourceManager.GetString("MenuItem_CenterCurrentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decline.
        /// </summary>
        public static string MenuItem_Decline {
            get {
                return ResourceManager.GetString("MenuItem_Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show directions.
        /// </summary>
        public static string MenuItem_Directions {
            get {
                return ResourceManager.GetString("MenuItem_Directions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email invite.
        /// </summary>
        public static string MenuItem_EmailInvite {
            get {
                return ResourceManager.GetString("MenuItem_EmailInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string MenuItem_Help {
            get {
                return ResourceManager.GetString("MenuItem_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        public static string MenuItem_Invite {
            get {
                return ResourceManager.GetString("MenuItem_Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set new roundup location.
        /// </summary>
        public static string MenuItem_NewRoundUpPoint {
            get {
                return ResourceManager.GetString("MenuItem_NewRoundUpPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purchase.
        /// </summary>
        public static string MenuItem_Purchase {
            get {
                return ResourceManager.GetString("MenuItem_Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update location.
        /// </summary>
        public static string MenuItem_RefreshLocation {
            get {
                return ResourceManager.GetString("MenuItem_RefreshLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location.
        /// </summary>
        public static string MenuItem_RefreshLocationShort {
            get {
                return ResourceManager.GetString("MenuItem_RefreshLocationShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restore previous session.
        /// </summary>
        public static string MenuItem_RestoreSession {
            get {
                return ResourceManager.GetString("MenuItem_RestoreSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share location via web.
        /// </summary>
        public static string MenuItem_ShareLocationNoRoundUp {
            get {
                return ResourceManager.GetString("MenuItem_ShareLocationNoRoundUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to directions.
        /// </summary>
        public static string MenuItem_ShowDirections {
            get {
                return ResourceManager.GetString("MenuItem_ShowDirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invitees.
        /// </summary>
        public static string MenuItem_ShowInvitees {
            get {
                return ResourceManager.GetString("MenuItem_ShowInvitees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sms invite.
        /// </summary>
        public static string MenuItem_SmsInvite {
            get {
                return ResourceManager.GetString("MenuItem_SmsInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sync device notifications.
        /// </summary>
        public static string MenuItem_Sync {
            get {
                return ResourceManager.GetString("MenuItem_Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show map controls.
        /// </summary>
        public static string MenuItem_ToggleMapControlPanel {
            get {
                return ResourceManager.GetString("MenuItem_ToggleMapControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  minutes.
        /// </summary>
        public static string MinutesText {
            get {
                return ResourceManager.GetString("MinutesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide the invite code that was sent to you by the person inviting you to meetup. 
        ///
        ///If you received the invite via SMS or email you can copy the entire message into the invite code box..
        /// </summary>
        public static string MissingInviteCode {
            get {
                return ResourceManager.GetString("MissingInviteCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitee.
        /// </summary>
        public static string MissingInviteeName {
            get {
                return ResourceManager.GetString("MissingInviteeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inviter.
        /// </summary>
        public static string MissingInviterName {
            get {
                return ResourceManager.GetString("MissingInviterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get the authentication required to use mapping. 
        ///
        ///Close the app (by tapping the back button on your device) and try agin later..
        /// </summary>
        public static string MissingMapAuthenticationCode {
            get {
                return ResourceManager.GetString("MissingMapAuthenticationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping error.
        /// </summary>
        public static string MissingMapAuthenticationCodeTitle {
            get {
                return ResourceManager.GetString("MissingMapAuthenticationCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel open failed. 
        ///
        ///This error was issued by the Microsoft push notification service. It indicates that the device could not be connected to the notification service.
        ///
        ///This error can be caused if the phone&apos;s date and time is not correctly set.
        ///
        ///It is recommended that you quit (by using the back button on the device) and then re-open the app.
        ///
        ///If you continue to get this error you may wish to review the roundup support page (see the link in the &apos;about&apos; screen), which has specific advice on this er [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MpnsChannelError_ChannelOpenFailed {
            get {
                return ResourceManager.GetString("MpnsChannelError_ChannelOpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification rate is too high.
        ///
        ///This error was issued by the Microsoft push notification service. It indicates that our roundup cloud service is requesting too many notifications be sent to this app.
        ///
        ///It is recommended that you quit (by using the back button on the device) and then re-open the app.
        ///
        ///If you continue to get this error you may wish to review the roundup support page (see the link in the &apos;about&apos; screen), which has specific advice on this error.
        /// </summary>
        public static string MpnsChannelError_NotificationRateTooHigh {
            get {
                return ResourceManager.GetString("MpnsChannelError_NotificationRateTooHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power level too low. 
        ///
        ///This error was issued by the Microsoft push notification service. It indicates that the power-level has dropped too low for the notification service to be used.
        ///
        ///It is recommended that you quit (by using the back button on the device), connect the device to a power source, and then re-open the app.
        ///
        ///If you continue to get this error you may wish to review the roundup support page (see the link in the &apos;about&apos; screen), which has specific advice on this error.
        /// </summary>
        public static string MpnsChannelError_PowerLevelChanged {
            get {
                return ResourceManager.GetString("MpnsChannelError_PowerLevelChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General failure. 
        ///
        ///This error was issued by the Microsoft push notification service. It indicates that an unknown or notification formatting-related problem has been encountered.
        ///
        ///It is recommended that you quit (by using the back button on the device) and then re-open the app.
        ///
        ///If you continue to get this error you may wish to review the roundup support page (see the link in the &apos;about&apos; screen), which has specific advice on this error.
        /// </summary>
        public static string MpnsChannelError_Unknown {
            get {
                return ResourceManager.GetString("MpnsChannelError_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPNS Error.
        /// </summary>
        public static string MpnsChannelErrorTitle {
            get {
                return ResourceManager.GetString("MpnsChannelErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Microsoft push notification system has indicated that this app has received too many notifications within a 24-period. 
        ///
        ///Try the operation again later..
        /// </summary>
        public static string MpnsLimitExceeded {
            get {
                return ResourceManager.GetString("MpnsLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPNS Error.
        /// </summary>
        public static string MpnsLimitExceededTitle {
            get {
                return ResourceManager.GetString("MpnsLimitExceededTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to complete the operation. The Microsoft push notification service is not responding.
        ///
        ///Try the operation again later..
        /// </summary>
        public static string MpnsTimedOut {
            get {
                return ResourceManager.GetString("MpnsTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPNS Error.
        /// </summary>
        public static string MpnsTimedOutTitle {
            get {
                return ResourceManager.GetString("MpnsTimedOutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to.
        /// </summary>
        public static string NewInviteeSuccessToast {
            get {
                return ResourceManager.GetString("NewInviteeSuccessToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string NewInviteeSuccessToastTitle {
            get {
                return ResourceManager.GetString("NewInviteeSuccessToastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new roundup session and invite code has been created. 
        ///
        ///You can share the invite code friends who have roundup. 
        ///
        ///Anybody you invite to join you will be able to see your location until the session ends or is cancelled..
        /// </summary>
        public static string NewSessionSuccess {
            get {
                return ResourceManager.GetString("NewSessionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New roundup session.
        /// </summary>
        public static string NewSessionSuccessTitle {
            get {
                return ResourceManager.GetString("NewSessionSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No address available.
        /// </summary>
        public static string NoAddress {
            get {
                return ResourceManager.GetString("NoAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no route directions to view..
        /// </summary>
        public static string NoDirections {
            get {
                return ResourceManager.GetString("NoDirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No directions.
        /// </summary>
        public static string NoDirectionsTitle {
            get {
                return ResourceManager.GetString("NoDirectionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the roundup cloud service has not yet delivered the necessary invite code to us.
        ///
        ///Try again later..
        /// </summary>
        public static string NoInviteCode {
            get {
                return ResourceManager.GetString("NoInviteCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No invite code.
        /// </summary>
        public static string NoInviteCodeTitle {
            get {
                return ResourceManager.GetString("NoInviteCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No invitees have accepted your invitation..
        /// </summary>
        public static string NoInvitees {
            get {
                return ResourceManager.GetString("NoInvitees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No invitees.
        /// </summary>
        public static string NoInviteesTitle {
            get {
                return ResourceManager.GetString("NoInviteesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not currently connected to the network. 
        ///
        ///Try again later..
        /// </summary>
        public static string NoNetworkConnection {
            get {
                return ResourceManager.GetString("NoNetworkConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current location is unknown. Update your location and try again.
        ///
        ///To update your location, click the &apos;location&apos; update button, or select the &apos;update location&apos; menu item.
        ///
        ///The GPS sensors in your device may not work correctly if you are indoors, or there are a lot a high buildings nearby..
        /// </summary>
        public static string NoStartNewSessionNoLocation {
            get {
                return ResourceManager.GetString("NoStartNewSessionNoLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location unknown.
        /// </summary>
        public static string NoStartNewSessionNoLocationTitle {
            get {
                return ResourceManager.GetString("NoStartNewSessionNoLocationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accept invite.
        /// </summary>
        public static string PaneAcceptInvite {
            get {
                return ResourceManager.GetString("PaneAcceptInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to directions.
        /// </summary>
        public static string PaneDirections {
            get {
                return ResourceManager.GetString("PaneDirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invitees.
        /// </summary>
        public static string PaneInviteeList {
            get {
                return ResourceManager.GetString("PaneInviteeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string PaneSettings {
            get {
                return ResourceManager.GetString("PaneSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        public static string PaneShare {
            get {
                return ResourceManager.GetString("PaneShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For your privacy and security:
        ///
        ///We do NOT store or transmit any information that uniquely identifies you.
        ///
        ///We do NOT access personal information (like your name, or any Microsoft account details).
        ///
        ///We do NOT store any information (either on the phone or in our cloud-based service) that could be used by unauthorized third-parties to track your location, gain access to personal data, or identify you or your phone.
        ///
        ///The user may disable or enable location (including background location tracking) and no [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PrivacyPolicy_Content {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancelling session.
        /// </summary>
        public static string ProgressBarTextCancelSession {
            get {
                return ResourceManager.GetString("ProgressBarTextCancelSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to changing roundup location.
        /// </summary>
        public static string ProgressBarTextChangeRoundUpPoint {
            get {
                return ResourceManager.GetString("ProgressBarTextChangeRoundUpPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to closing roundup session.
        /// </summary>
        public static string ProgressBarTextCloseSession {
            get {
                return ResourceManager.GetString("ProgressBarTextCloseSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getting your location.
        /// </summary>
        public static string ProgressBarTextConnecting {
            get {
                return ResourceManager.GetString("ProgressBarTextConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creating roundup session.
        /// </summary>
        public static string ProgressBarTextCreateSession {
            get {
                return ResourceManager.GetString("ProgressBarTextCreateSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to joining roundup session.
        /// </summary>
        public static string ProgressBarTextJoiningSession {
            get {
                return ResourceManager.GetString("ProgressBarTextJoiningSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are running the trial version of this app. 
        ///
        ///The trial period will expire in {0} days, after which you must either purchase or uninstall the app..
        /// </summary>
        public static string PurchaseReminder {
            get {
                return ResourceManager.GetString("PurchaseReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Reminder.
        /// </summary>
        public static string PurchaseReminderTitle {
            get {
                return ResourceManager.GetString("PurchaseReminderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been using roundup for a while now. We really hope you&apos;re finding it useful.
        ///
        ///We&apos;d love it if you&apos;d give us a rating in the store. This will help spread the word about roundup, and your feedback will help us make things even better in future versions!
        ///
        ///Click &apos;ok&apos; to rate this app in the store, or click &apos;cancel&apos; to continue using roundup.
        ///
        ///You will not be reminded again to rate this app - we&apos;d hate to nag!!.
        /// </summary>
        public static string RateAppReminder {
            get {
                return ResourceManager.GetString("RateAppReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoying roundup?.
        /// </summary>
        public static string RateAppReminderTitle {
            get {
                return ResourceManager.GetString("RateAppReminderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you give permission for roundup to use location services on this device? 
        ///
        ///Background location tracking and the ability to run while the lock screen is engaged are turned on by default. 
        ///
        ///All location service features may be disabled or enabled at any time from the &apos;settings&apos; screen.
        ///
        ///This app&apos;s use of your location is described in the app&apos;s Full Privacy Policy (see the &apos;about&apos; screen)..
        /// </summary>
        public static string RequestPermissionLocationServices {
            get {
                return ResourceManager.GetString("RequestPermissionLocationServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Permission.
        /// </summary>
        public static string RequestPermissionLocationServicesTitle {
            get {
                return ResourceManager.GetString("RequestPermissionLocationServicesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you give permission for roundup to use notifications sent by the Microsoft push notification system? 
        ///
        ///Notifications contain data related to your location, and are described in the app&apos;s Full Privacy Policy (see the &apos;about&apos; screen). 
        ///
        ///Notifications may be turned on/off in the &apos;settings&apos; screen..
        /// </summary>
        public static string RequestPermissionMpns {
            get {
                return ResourceManager.GetString("RequestPermissionMpns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Permission.
        /// </summary>
        public static string RequestPermissionMpnsTitle {
            get {
                return ResourceManager.GetString("RequestPermissionMpnsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet here.
        /// </summary>
        public static string RoundUpLocationMarker {
            get {
                return ResourceManager.GetString("RoundUpLocationMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated time of arrival {0}.
        /// </summary>
        public static string RouteInstructionEta {
            get {
                return ResourceManager.GetString("RouteInstructionEta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested roundup session does not exist. 
        ///
        ///The session may have expired or been cancelled, or you may have entered the wrong invite code.
        ///
        ///Check the code and try again..
        /// </summary>
        public static string SessionDoesNotExist {
            get {
                return ResourceManager.GetString("SessionDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session not found.
        /// </summary>
        public static string SessionDoesNotExistTitle {
            get {
                return ResourceManager.GetString("SessionDoesNotExistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session has been successfully cancelled..
        /// </summary>
        public static string SessionHasBeenCancelled {
            get {
                return ResourceManager.GetString("SessionHasBeenCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has cancelled the current roundup session - sorry!.
        /// </summary>
        public static string SessionHasBeenCancelledByInviter {
            get {
                return ResourceManager.GetString("SessionHasBeenCancelledByInviter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session cancelled.
        /// </summary>
        public static string SessionHasBeenCancelledByInviterTitle {
            get {
                return ResourceManager.GetString("SessionHasBeenCancelledByInviterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session cancelled..
        /// </summary>
        public static string SessionHasBeenCancelledTitle {
            get {
                return ResourceManager.GetString("SessionHasBeenCancelledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested roundup session is not active. 
        ///
        ///The session may have expired or been cancelled, or you may have entered the wrong invite code.
        ///
        ///Check the code and try again..
        /// </summary>
        public static string SessionIsNotAlive {
            get {
                return ResourceManager.GetString("SessionIsNotAlive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired roundup session.
        /// </summary>
        public static string SessionIsNotAliveTitle {
            get {
                return ResourceManager.GetString("SessionIsNotAliveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click OK, then tap anywhere on the map to set a new roundup point. 
        ///
        ///Alternatively, click cancel to use your current location as the roundup point..
        /// </summary>
        public static string SetNewRoundUpPointPrompt {
            get {
                return ResourceManager.GetString("SetNewRoundUpPointPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new roundup location.
        /// </summary>
        public static string SetNewRoundUpPointPromptTitle {
            get {
                return ResourceManager.GetString("SetNewRoundUpPointPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Phone.
        /// </summary>
        public static string Settings_Alias_DefaultValue {
            get {
                return ResourceManager.GetString("Settings_Alias_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name/alias. Used in notifications and as part of any roundup invite. You don&apos;t need to provide your real name (this app does not send any information that personally identifies you or your device to third parties)..
        /// </summary>
        public static string SettingsPane_AliasTitle {
            get {
                return ResourceManager.GetString("SettingsPane_AliasTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always show directions to the roundup location..
        /// </summary>
        public static string SettingsPane_AlwaysShowsDirections {
            get {
                return ResourceManager.GetString("SettingsPane_AlwaysShowsDirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when I&apos;m invited.
        /// </summary>
        public static string SettingsPane_AlwaysShowsDirectionsInvitee {
            get {
                return ResourceManager.GetString("SettingsPane_AlwaysShowsDirectionsInvitee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when I start the meeting.
        /// </summary>
        public static string SettingsPane_AlwaysShowsDirectionsInviter {
            get {
                return ResourceManager.GetString("SettingsPane_AlwaysShowsDirectionsInviter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow the app to run in the background and track location. This is optional (it isn&apos;t a requirement for correct operation)..
        /// </summary>
        public static string SettingsPane_BackgroundExecution {
            get {
                return ResourceManager.GetString("SettingsPane_BackgroundExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn location services on or off. If you turn this feature off, the app will not be able to operate.
        ///
        ///This app&apos;s use of location services is described in the Full Privacy Policy (see the &apos;about&apos; screen)..
        /// </summary>
        public static string SettingsPane_LocationServicesOnOff {
            get {
                return ResourceManager.GetString("SettingsPane_LocationServicesOnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn location tracking on or off. If you turn this feature off, the app will not be able to operate..
        /// </summary>
        public static string SettingsPane_LocationTrackingOnOff {
            get {
                return ResourceManager.GetString("SettingsPane_LocationTrackingOnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn push notifications on or off. If you turn this feature off, the app will not be able to operate. 
        ///
        ///This app&apos;s use of push notifications is described in the Full Privacy Policy (see the &apos;about&apos; screen).
        /// </summary>
        public static string SettingsPane_MpnsOnOff {
            get {
                return ResourceManager.GetString("SettingsPane_MpnsOnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow the app to run when the lock screen is engaged. This is optional (it isn&apos;t a requirement for correct operation)..
        /// </summary>
        public static string SettingsPane_RunUnderLockScreen {
            get {
                return ResourceManager.GetString("SettingsPane_RunUnderLockScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When restarting the app, if a time period greater than the following value has elapsed, no attempt will be made to restore the previous session..
        /// </summary>
        public static string SettingsPane_SessionDeadTimeout {
            get {
                return ResourceManager.GetString("SettingsPane_SessionDeadTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow toast notifications when the app is running in the background.
        ///
        ///These notifcations tell you when somebody has joined a roundup session, you&apos;ve arrived, etc..
        /// </summary>
        public static string SettingsPane_ToastOnOff {
            get {
                return ResourceManager.GetString("SettingsPane_ToastOnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clipboard.
        /// </summary>
        public static string ShareClipboard {
            get {
                return ResourceManager.GetString("ShareClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share your location.
        /// </summary>
        public static string ShareComment {
            get {
                return ResourceManager.GetString("ShareComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        public static string ShareEmail {
            get {
                return ResourceManager.GetString("ShareEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sms.
        /// </summary>
        public static string ShareSms {
            get {
                return ResourceManager.GetString("ShareSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the person I&apos;m sharing with has roundup.
        /// </summary>
        public static string ShareTargetHasRoundUp {
            get {
                return ResourceManager.GetString("ShareTargetHasRoundUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A roundup invite code has been added to the clipboard. 
        ///
        ///You can send this code to friends that have roundup. Once they accept your invite you&apos;ll be able to see them on the map, and they&apos;ll be able to see your location on their map..
        /// </summary>
        public static string ShareViaClipboard {
            get {
                return ResourceManager.GetString("ShareViaClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share via roundup.
        /// </summary>
        public static string ShareViaClipboardTitle {
            get {
                return ResourceManager.GetString("ShareViaClipboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to roundup : no session.
        /// </summary>
        public static string TileNoSession {
            get {
                return ResourceManager.GetString("TileNoSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite your friends to meetup.
        /// </summary>
        public static string TileNoSessionMsg {
            get {
                return ResourceManager.GetString("TileNoSessionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a new roundup session and invite your friends to join you.
        /// </summary>
        public static string TileNoSessionWideMsg {
            get {
                return ResourceManager.GetString("TileNoSessionWideMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to roundup : tracking.
        /// </summary>
        public static string TileSessionInProgress {
            get {
                return ResourceManager.GetString("TileSessionInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting up with .
        /// </summary>
        public static string TileSessionInProgressInvitee {
            get {
                return ResourceManager.GetString("TileSessionInProgressInvitee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody has accepted your invite..
        /// </summary>
        public static string TileSessionInProgressNoInvitees {
            get {
                return ResourceManager.GetString("TileSessionInProgressNoInvitees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  friends have accepted your invite..
        /// </summary>
        public static string TileSessionInProgressWithInvitees {
            get {
                return ResourceManager.GetString("TileSessionInProgressWithInvitees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 friend has accepted your invite..
        /// </summary>
        public static string TileSessionInProgressWithOneInvitee {
            get {
                return ResourceManager.GetString("TileSessionInProgressWithOneInvitee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the maximum number of invitees permitted on a session has been reached..
        /// </summary>
        public static string TooManyInvitees {
            get {
                return ResourceManager.GetString("TooManyInvitees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to join session.
        /// </summary>
        public static string TooManyInviteesTitle {
            get {
                return ResourceManager.GetString("TooManyInviteesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trial period for this app has expired. 
        ///
        ///You must now either purchase roundup from the store, or uninstall it..
        /// </summary>
        public static string TrialHasExpired {
            get {
                return ResourceManager.GetString("TrialHasExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Expired.
        /// </summary>
        public static string TrialHasExpiredTitle {
            get {
                return ResourceManager.GetString("TrialHasExpiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to restore previous session.
        ///
        ///Create a new session and invite others to join you..
        /// </summary>
        public static string UnableToRestorePreviousSession {
            get {
                return ResourceManager.GetString("UnableToRestorePreviousSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot restore session.
        /// </summary>
        public static string UnableToRestorePreviousSessionTitle {
            get {
                return ResourceManager.GetString("UnableToRestorePreviousSessionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string ViewAbout {
            get {
                return ResourceManager.GetString("ViewAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string ViewHelp {
            get {
                return ResourceManager.GetString("ViewHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location.
        /// </summary>
        public static string ViewMain {
            get {
                return ResourceManager.GetString("ViewMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string ViewSettings {
            get {
                return ResourceManager.GetString("ViewSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waiting for notification (cancel invitee).
        /// </summary>
        public static string WaitingForNotification_CancelInvitee {
            get {
                return ResourceManager.GetString("WaitingForNotification_CancelInvitee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waiting for notification (cancel session).
        /// </summary>
        public static string WaitingForNotification_CancelSession {
            get {
                return ResourceManager.GetString("WaitingForNotification_CancelSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waiting for notification (new invitee).
        /// </summary>
        public static string WaitingForNotification_InviteeId {
            get {
                return ResourceManager.GetString("WaitingForNotification_InviteeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waiting for notification (new session).
        /// </summary>
        public static string WaitingForNotification_SessionId {
            get {
                return ResourceManager.GetString("WaitingForNotification_SessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waiting for push notification service.
        /// </summary>
        public static string WaitingForPushNotificationService {
            get {
                return ResourceManager.GetString("WaitingForPushNotificationService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to accept an invite from.
        /// </summary>
        public static string WantToAcceptInvite {
            get {
                return ResourceManager.GetString("WantToAcceptInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept invite?.
        /// </summary>
        public static string WantToAcceptInviteTitle {
            get {
                return ResourceManager.GetString("WantToAcceptInviteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attempting to restore session.
        /// </summary>
        public static string WillAttemptSessionRestore {
            get {
                return ResourceManager.GetString("WillAttemptSessionRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have arrived.
        /// </summary>
        public static string YouHaveArrived {
            get {
                return ResourceManager.GetString("YouHaveArrived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrived!.
        /// </summary>
        public static string YouHaveArrivedTitle {
            get {
                return ResourceManager.GetString("YouHaveArrivedTitle", resourceCulture);
            }
        }
    }
}
